#!/usr/bin/env bash
# Script to transfer a file from our client to a server

# Check if less that 4 parameters are passed
if [ "$#" -lt 4 ]; then
	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

# Assigning the input parameters to variables
FILE_PATH=$1
SERVER_IP=$2
USERNAME=$3
PRIVATE_KEY_PATH=$4

# Using SCP to transfer the file to the user's home directory
scp -i "$PRIVATE_KEY_PATH" "$FILE_PATH" -o StrictHostKeyChecking=no "$FILE_PATH" "$USERNAME"@"$SERVER_IP":~/
