#!/bin/bash

# update the package list
sudo apt-get update

# Install nginx
sudo apt-get install -y nginx

# Create a new nginx cofiguration file
echo "server {
    listen 80;
    location / {
        return 200 'Hello World!\n';
	add_header Content-Type text/plain;
    }
}" | sudo tee /etc/nginx/sites-available/default

# Reload nginx to apply the changes
sudo service nginx reload
