#!/usr/bin/env bash
# Installs Nginx

# update the package list
sudo apt-get update

# Install nginx
sudo apt-get install -y nginx

# Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Reload nginx to apply the changes
sudo service nginx restart
