#!/usr/bin/env bash
# Installs Nginx and configures redirection

# Update the package list
sudo apt-get update

# Install nginx
sudo apt-get install -y nginx

# Create a new nginx configuration file
printf "server {
	listen 80;
	location / {
	    return 200 'Hello World!\\n';
	    add_header Content-Type text/plain;
	}
	location = /redirect_me {
	    return 301 http://gikonyomwema.tech/new_page;
	}
}" | sudo tee /etc/nginx/sites-available/default

# Reload nginx to apply the changes
sudo service nginx restart
