#!/usr/bin/env bash
# Redirection - 301 moved permanently

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello world!" | sudo tee /var/www/html/index.html

replacement_str="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/gikonyo-mwema permanent;"

sudo sed -i "s/server_name _;/$replacement_str/" /etc/nginx/sites-enabled/default

sudo service nginx restart
