#!/usr/bin/env bash
#configures a new Ubuntu machine nginx
sudo apt-get update
sudo apt-get install -y haproxy
echo "frontend web-front
        bind *:80
        default_backend web-backend

backend web-backend
        balance roundrobin
        server web1 54.157.151.166:80 check
        server web2 18.210.33.196:80 check
" | sudo tee /etc/haproxy/haproxy.cfg
sudo systemctl restart haproxy
