#!/bin/bash

# Update the system
sudo apt-get update

# Install HAProxy
sudo apt-get install -y haproxy

# Define the configuration
CONFIG="
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
   bind *:80
   stats uri /haproxy?stats
   default_backend http_back

backend http_back
   balance roundrobin
   server 271621-web-01 54.157.151.166:80 check
   server 271621-web-02 18.210.33.196:80 check
"

# Write the configuration to the HAProxy configuration file
echo "$CONFIG" | sudo tee /etc/haproxy/haproxy.cfg

# Restart HAProxy to apply the changes
sudo service haproxy restart

