#!/usr/bin/env bash
# This script displays numbers from 1 to 100
# replacing multiples of 3 and 5

for i in {1..100}
do
    if (( i % 3 == 0 && 5 == 0)); then
        echo "FizzBuzz"
    elif (( i % 3 == 0 )); then
        echo "Fizz"
    elif (( i % 5 == 0 )); then
        echo "Buzz"
    else
        echo "$i"
    fi
done
