#!/usr/bin/env bash
# This script displays the usename, user ID and home director
# from /etc/passwd

while IFS=: read -r username _ userid _ _ homedir _
do
    echo "$username:$userid:$homedir"
done < /etc/passwd
