#!/usr/bin/env bash
#This script is displaying "Best School" 10 times
#Initialize counter
counter=1

#Use a while loop to print the phrase 10 times
while ((counter <= 10))
do
    echo "Best School"
    ((counter++))
done
