#!/usr/bin/env bash
# Script displays numbers from 1 to 20 and custom phrases for 4, 9 and 17

# Initialize coutner
counter=1

# Start the while loop
while [ $counter -le 20 ]
do
    # Display the counter
    echo $counter

    # Use a case statement
    case $counter in
        4)
            echo "Bad luck from China"
            ;;
        9)
            echo "Bad luck from Japan"
            ;;
        17)
            echo "Bad luck from Italy"
            ;;
    esac

    # Increment the counter
    ((counter++))
done
