#!/usr/bin/env bash
# The ssh-keygen command is used to generate a new SSH key pair.
# The -t flag is used to specif the type of key
# The -b flag is used to specify the number of bits
# The -f flag is used to specify the filename of the key
# The -N flag is used to specify the passphrase of the key
ssh-keygen -t rsa -b 4096 -f ~/.ssh/school -N betty
